### ISSUE TITLE
Hidden field adds a Label, it should not.

### ISSUE THREAD

**Issue by paganotoni** [wawandco/tailush#2]
Hidden fields should only render the field given these are not intended to be seen. Currently we're generating the label as well.

cc @SirUela

**Comment by SirUela** [comment]
@paganotoni  In the visual example I use, I don't see any label.

![image](https://user-images.githubusercontent.com/63132183/216649035-68c68a07-c81f-4b10-a5b9-b6b28782910f.png)

Could you provide more information or steps on how to reproduce it?

PD: **Tailush Hidden** is a div put by me, not an actual label

**Comment by paganotoni** [comment]
Sure thing, oh I see. I had:

```
 <%= f.InputTag("Notes", {type: "hidden"}) %>
 ```
 
 Which should render a hidden tag. But now I see I should have used:
 ```
  <%= f.HiddenTag("Notes"}) %>
 ```

**Comment by SirUela** [comment]
I was checking and in the **formfor.go** we have a wrapper around the **InputTag** function

```go
func (f formFor) InputTag(field string, opts tags.Options) *tags.Tag {
	f.buildOptions(field, opts)
	f.addFormatTag(field, opts)

	return divWrapper(opts, func(opts tags.Options) tags.Body {
		return f.form.InputTag(opts)
	})
}
```

That wrapper doesn't care about the <input> type, that's why it is generating that label. We should probably return the **InputTag** directly if `type == "hidden" `
